Repository MarketPlace-O2O-Platform/MarketPlace-Server, pull requests merged in 2024-10, with the labels that each got.

#13 [Refactor/#11] 마켓 유효성 검사 및 예외처리
  src/main/java/com/appcenter/marketplace/domain/market/Market.java
  src/main/java/com/appcenter/marketplace/domain/market/controller/MarketOwnerController.java
  src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketOwnerServiceImpl.java
  src/main/java/com/appcenter/marketplace/global/common/StatusCode.java
Labels: 리팩토링

#16 [Refactor/#12] 쿠폰 유효성 검사 및 예외처리 로직 수정
  build.gradle
  src/main/java/com/appcenter/marketplace/domain/coupon/controller/CouponController.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/impl/CouponServiceImpl.java
  src/main/java/com/appcenter/marketplace/global/common/StatusCode.java
Labels: 리팩토링

#17 [Env/#14] 다중 DB 연결을 위한 Config 설정 및 교내 학생 인증 쿼리 추가
  build.gradle
  src/main/java/com/appcenter/marketplace/global/config/MysqlConfig.java
  src/main/java/com/appcenter/marketplace/global/config/OracleConfig.java
  src/main/java/com/appcenter/marketplace/global/oracleRepository/InuLoginRepository.java
  src/main/resources/application.properties
Labels: 환경 설정

#19 [Feat/#18] ci/cd.yml 배포
  .github/workflows/cicd.yml
Labels: 기능구현, 환경 설정

#24 [Feat/#23] INU 학번 로그인 기능 구현 + MySQL 테이블명 고정 설정 + 프로퍼티 파일 구분
  src/main/java/com/appcenter/marketplace/MarketplaceApplication.java
  src/main/java/com/appcenter/marketplace/domain/category/Category.java
  src/main/java/com/appcenter/marketplace/domain/coupon/Coupon.java
  src/main/java/com/appcenter/marketplace/domain/coupon/controller/CouponController.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/req/CouponReqDto.java
  src/main/java/com/appcenter/marketplace/domain/favorite/Favorite.java
  src/main/java/com/appcenter/marketplace/domain/image/Image.java
  src/main/java/com/appcenter/marketplace/domain/market/Market.java
  src/main/java/com/appcenter/marketplace/domain/member/Member.java
  src/main/java/com/appcenter/marketplace/domain/member/MemberRepository.java
  src/main/java/com/appcenter/marketplace/domain/member/controller/MemberController.java
  src/main/java/com/appcenter/marketplace/domain/member/dto/req/MemberLoginReqDto.java
  src/main/java/com/appcenter/marketplace/domain/member/dto/res/MemberLoginResDto.java
  src/main/java/com/appcenter/marketplace/domain/member/service/MemberService.java
  src/main/java/com/appcenter/marketplace/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/member_coupon/MemberCoupon.java
  src/main/java/com/appcenter/marketplace/global/common/Major.java
  src/main/java/com/appcenter/marketplace/global/common/StatusCode.java
  src/main/java/com/appcenter/marketplace/global/config/OracleConfig.java
  src/main/java/com/appcenter/marketplace/global/oracleRepository/InuLoginRepository.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: 기능구현, 리팩토링, 환경 설정

#26 [Refactor/#25] Swagger 서버 URL 프로퍼티 파일 분리
  src/main/java/com/appcenter/marketplace/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/appcenter/marketplace/global/config/OracleConfig.java
  src/main/java/com/appcenter/marketplace/global/config/SwaggerConfig.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
Labels: 리팩토링

#28 [Feat/#27] 이미지 테이블 경로 단일 컬럼으로 수정, 이미지 업로드 기능 구현 및 리소스 핸들러 설정 추가
  .env
  .github/workflows/cicd.yml
  .gitignore
  docker-compose.yml
  local/docker-compose.yml
  src/main/java/com/appcenter/marketplace/domain/image/Image.java
  src/main/java/com/appcenter/marketplace/domain/image/ImageRepository.java
  src/main/java/com/appcenter/marketplace/domain/image/service/ImageService.java
  src/main/java/com/appcenter/marketplace/domain/image/service/impl/ImageServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/Market.java
  src/main/java/com/appcenter/marketplace/domain/market/controller/MarketOwnerController.java
  src/main/java/com/appcenter/marketplace/domain/market/service/MarketOwnerService.java
  src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketOwnerServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/appcenter/marketplace/global/common/StatusCode.java
  src/main/java/com/appcenter/marketplace/global/config/ImageConfig.java
  src/main/java/com/appcenter/marketplace/global/exception/ExceptionControllerAdvice.java
  src/main/java/com/appcenter/marketplace/global/oracleRepository/InuLoginRepository.java
  src/main/java/com/appcenter/marketplace/global/swagger/OctetStreamReadMsgConverter.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
Labels: 기능구현, 리팩토링, 환경 설정

#33 [Feat/#31] QueryDSL 기본 설정
  build.gradle
  src/main/generated/com/appcenter/marketplace/domain/category/QCategory.java
  src/main/generated/com/appcenter/marketplace/domain/coupon/QCoupon.java
  src/main/generated/com/appcenter/marketplace/domain/favorite/QFavorite.java
  src/main/generated/com/appcenter/marketplace/domain/image/QImage.java
  src/main/generated/com/appcenter/marketplace/domain/market/QMarket.java
  src/main/generated/com/appcenter/marketplace/domain/member/QMember.java
  src/main/generated/com/appcenter/marketplace/domain/member_coupon/QMemberCoupon.java
  src/main/generated/com/appcenter/marketplace/global/common/QBaseEntity.java
  src/main/java/com/appcenter/marketplace/global/config/QuerydslConfig.java
Labels: 기능구현, 환경 설정
