Repository MarketPlace-O2O-Platform/MarketPlace-Server, pull requests merged in 2024-12, with the labels that each got.

#76 [Feat/#75] 주소 별 매장 리스트 조회 API 구현
  src/main/java/com/appcenter/marketplace/domain/market/controller/MarketController.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/service/MarketService.java
  src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketServiceImpl.java
Labels: 기능구현

#74 [Issue/#73] 매장 리스트 조회 시 신규 쿠폰 여부 추가
  src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QFavoriteMarketRes.java
  src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QMarketRes.java
  src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QMyFavoriteMarketRes.java
  src/main/java/com/appcenter/marketplace/domain/market/controller/MarketController.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/res/FavoriteMarketRes.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/res/MarketRes.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/res/MyFavoriteMarketRes.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/service/MarketService.java
  src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketServiceImpl.java
Labels: 기능구현, 이슈해결

#77 [Issue/#72] 최신 등록 쿠폰 리스트 찜 여부 추가 + memberId 별 찜 여부 추가
  src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QLatestCouponRes.java
  src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QTopLatestCouponRes.java
  src/main/java/com/appcenter/marketplace/domain/market/controller/MarketController.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/res/LatestCouponRes.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/res/TopLatestCouponRes.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/service/MarketService.java
  src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketServiceImpl.java
Labels: 기능구현, 리팩토링, 이슈해결

#80 [Issue/#79] Top 인기 매장 리스트 찜 여부 누락 구현
  src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QTopFavoriteMarketRes.java
  src/main/java/com/appcenter/marketplace/domain/market/controller/MarketController.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/res/TopFavoriteMarketRes.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/service/MarketService.java
  src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketServiceImpl.java
Labels: 기능구현, 이슈해결

#81 [Feat/#78] 최신 쿠폰 리스트 "신규 쿠폰" 태그 추가
  src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QLatestCouponRes.java
  src/main/java/com/appcenter/marketplace/domain/market/controller/MarketController.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/res/LatestCouponRes.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/service/MarketService.java
  src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketServiceImpl.java
Labels: 기능구현, 리팩토링, 이슈해결

#83 [Feat/#82] 요청, 임시, 응원 테이블 추가 생성 및 회원 응원권 컬럼 추가
  src/main/generated/com/appcenter/marketplace/domain/cheer/QCheer.java
  src/main/generated/com/appcenter/marketplace/domain/member/QMember.java
  src/main/generated/com/appcenter/marketplace/domain/requestMarket/QRequestMarket.java
  src/main/generated/com/appcenter/marketplace/domain/tempMarket/QTempMarket.java
  src/main/java/com/appcenter/marketplace/domain/cheer/Cheer.java
  src/main/java/com/appcenter/marketplace/domain/member/Member.java
  src/main/java/com/appcenter/marketplace/domain/requestMarket/RequestMarket.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/TempMarket.java
Labels: 기능구현
