Repository MarketPlace-O2O-Platform/MarketPlace-Server, pull requests merged in 2024-11, with the labels that each got.

#34 [Feat/#32] 매장 이미지 수정 기능 추가, 매장 응답 DTO 및 조회 로직 변경, 매장 삭제 시 이미지 삭제 로직 추가
  src/main/generated/com/appcenter/marketplace/domain/image/QImage.java
  src/main/generated/com/appcenter/marketplace/domain/image/dto/res/QImageResDto.java
  src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QMarketResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/impl/CouponServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/image/Image.java
  src/main/java/com/appcenter/marketplace/domain/image/ImageRepository.java
  src/main/java/com/appcenter/marketplace/domain/image/dto/res/ImageResDto.java
  src/main/java/com/appcenter/marketplace/domain/image/service/ImageService.java
  src/main/java/com/appcenter/marketplace/domain/image/service/impl/ImageServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/MarketRepository.java
  src/main/java/com/appcenter/marketplace/domain/market/controller/MarketOwnerController.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/req/MarketImageUpdateReqDto.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/res/MarketResDto.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepository.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/service/MarketOwnerService.java
  src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketOwnerServiceImpl.java
  src/main/java/com/appcenter/marketplace/global/common/StatusCode.java
  src/main/java/com/appcenter/marketplace/global/exception/ExceptionControllerAdvice.java
Labels: 기능구현, 리팩토링

#37 [Feat/#35] 매장 정보 조회 통합 api MarketOwnerController,Service-> MarketController,Service 옮김
  src/main/java/com/appcenter/marketplace/domain/market/controller/MarketController.java
  src/main/java/com/appcenter/marketplace/domain/market/controller/MarketOwnerController.java
  src/main/java/com/appcenter/marketplace/domain/market/service/MarketOwnerService.java
  src/main/java/com/appcenter/marketplace/domain/market/service/MarketService.java
  src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketOwnerServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketServiceImpl.java
Labels: 기능구현, 리팩토링

#40 [Refactor/#38] 이미지 테이블 sequence 컬럼 unique 제약조건으로 인한 이미지 순서 변경 로직 보완
  src/main/java/com/appcenter/marketplace/domain/image/service/impl/ImageServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/controller/MarketOwnerController.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/req/MarketImageUpdateReqDto.java
  src/main/java/com/appcenter/marketplace/global/common/StatusCode.java
Labels: 기능구현, 리팩토링

#42 [Feat/#41] 매장 찜하기 API 구현
  src/main/java/com/appcenter/marketplace/domain/favorite/Favorite.java
  src/main/java/com/appcenter/marketplace/domain/favorite/FavoriteRepository.java
  src/main/java/com/appcenter/marketplace/domain/favorite/controller/FavoriteController.java
  src/main/java/com/appcenter/marketplace/domain/favorite/service/FavoriteService.java
  src/main/java/com/appcenter/marketplace/domain/favorite/service/impl/FavoriteServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/res/MarketResDto.java
  src/main/java/com/appcenter/marketplace/global/common/StatusCode.java
Labels: 기능구현

#45 [Feat/#43] 전체 매장 리스트 페이지 조회 API 구현
  src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QMarketDetailsResDto.java
  src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QMarketResDto.java
  src/main/java/com/appcenter/marketplace/domain/category/Category.java
  src/main/java/com/appcenter/marketplace/domain/market/controller/MarketController.java
  src/main/java/com/appcenter/marketplace/domain/market/controller/MarketOwnerController.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/res/MarketDetailsResDto.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/res/MarketPageResDto.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/res/MarketResDto.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/service/MarketOwnerService.java
  src/main/java/com/appcenter/marketplace/domain/market/service/MarketService.java
  src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketOwnerServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketServiceImpl.java
Labels: 기능구현, 리팩토링

#47 [Feat/#46,#48] 찜한 매장 리스트 조회 API 구현, 가장 많은 찜 순 매장 리스트 조회 API 구현
  src/main/java/com/appcenter/marketplace/domain/favorite/controller/FavoriteController.java
  src/main/java/com/appcenter/marketplace/domain/favorite/repository/FavoriteRepository.java
  src/main/java/com/appcenter/marketplace/domain/favorite/repository/FavoriteRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/favorite/repository/FavoriteRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/favorite/service/FavoriteService.java
  src/main/java/com/appcenter/marketplace/domain/favorite/service/impl/FavoriteServiceImpl.java
Labels: 기능구현

#39 [Feat/#22] 회원 쿠폰 발급 및 사용 처리 API & 사장님 및 회원 QueryDSL 적용
  .gitignore
  src/main/generated/com/appcenter/marketplace/domain/member_coupon/dto/res/QIssuedMemberCouponResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/Coupon.java
  src/main/java/com/appcenter/marketplace/domain/coupon/CouponRepository.java
  src/main/java/com/appcenter/marketplace/domain/coupon/controller/CouponController.java
  src/main/java/com/appcenter/marketplace/domain/coupon/controller/CouponOwnerController.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/req/CouponUpdateReqDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponListResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponMemberResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/repository/CouponRepository.java
  src/main/java/com/appcenter/marketplace/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/coupon/repository/CouponRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/CouponOwnerService.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/CouponService.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/impl/CouponOwnerServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/impl/CouponServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/member_coupon/MemberCoupon.java
  src/main/java/com/appcenter/marketplace/domain/member_coupon/MemberCouponRepository.java
  src/main/java/com/appcenter/marketplace/domain/member_coupon/controller/MemberCouponController.java
  src/main/java/com/appcenter/marketplace/domain/member_coupon/dto/req/MemberCouponReqDto.java
  src/main/java/com/appcenter/marketplace/domain/member_coupon/dto/res/IssuedMemberCouponResDto.java
  src/main/java/com/appcenter/marketplace/domain/member_coupon/dto/res/MemberCouponUpdateResDto.java
  src/main/java/com/appcenter/marketplace/domain/member_coupon/repository/MemberCouponRepository.java
  src/main/java/com/appcenter/marketplace/domain/member_coupon/repository/MemberCouponRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/member_coupon/repository/MemberCouponRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/member_coupon/service/MemberCouponService.java
  src/main/java/com/appcenter/marketplace/domain/member_coupon/service/impl/MemberCouponServiceImpl.java
  src/main/java/com/appcenter/marketplace/global/common/StatusCode.java
  src/main/java/com/appcenter/marketplace/global/config/QuerydslConfig.java
Labels: 기능구현, 문서화, 환경 설정

#55 [Refactor/#54] Favorite 매장 조회 Api -> Market 매장 조회 Api로 변경
  src/main/java/com/appcenter/marketplace/domain/favorite/controller/FavoriteController.java
  src/main/java/com/appcenter/marketplace/domain/favorite/repository/FavoriteRepository.java
  src/main/java/com/appcenter/marketplace/domain/favorite/repository/FavoriteRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/favorite/repository/FavoriteRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/favorite/service/FavoriteService.java
  src/main/java/com/appcenter/marketplace/domain/favorite/service/impl/FavoriteServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/controller/MarketController.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/service/MarketService.java
  src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketServiceImpl.java
Labels: 리팩토링, 디자인

#57 [Feat] 광역시/도 & 시/구 테이블 생성 - #56
  src/main/java/com/appcenter/marketplace/domain/local/Local.java
  src/main/java/com/appcenter/marketplace/domain/metro/Metro.java
Labels: 기능구현

#52 [Feat/#51] 최신 등록 쿠폰 TOP5 & 전체 리스트 조회 API 구현
  src/main/generated/com/appcenter/marketplace/domain/coupon/dto/res/QCouponLatestTopResDto.java
  src/main/generated/com/appcenter/marketplace/domain/coupon/dto/res/QCouponMarketResDto.java
  src/main/generated/com/appcenter/marketplace/domain/coupon/dto/res/QCouponMemberResDto.java
  src/main/generated/com/appcenter/marketplace/domain/coupon/dto/res/QCouponResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/controller/CouponController.java
  src/main/java/com/appcenter/marketplace/domain/coupon/controller/CouponOwnerController.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponLatestTopResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponListResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponMarketPageResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponMarketResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponMemberResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/coupon/repository/CouponRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/CouponOwnerService.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/CouponService.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/impl/CouponOwnerServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/impl/CouponServiceImpl.java
Labels: 기능구현, 문서화

#58 [Feat/#53] 마감임박 쿠폰 TOP 5 조회 리스트 API 구현
  src/main/generated/com/appcenter/marketplace/domain/coupon/dto/res/QCouponClosingTopResDto.java
  src/main/generated/com/appcenter/marketplace/domain/coupon/dto/res/QCouponLatestTopResDto.java
  src/main/generated/com/appcenter/marketplace/domain/coupon/dto/res/QCouponMarketResDto.java
  src/main/generated/com/appcenter/marketplace/domain/coupon/dto/res/QCouponMemberResDto.java
  src/main/generated/com/appcenter/marketplace/domain/coupon/dto/res/QCouponResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/controller/CouponController.java
  src/main/java/com/appcenter/marketplace/domain/coupon/controller/CouponOwnerController.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponClosingTopResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponLatestTopResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponListResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponMarketPageResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponMarketResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponMemberResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/coupon/repository/CouponRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/CouponOwnerService.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/CouponService.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/impl/CouponOwnerServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/impl/CouponServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/member/Member.java
Labels: 기능구현, 리팩토링, 문서화

#61 [Feat/#60] 쿠폰 발급 시, 0개인 경우 에러 메세지 추가
  src/main/generated/com/appcenter/marketplace/domain/coupon/dto/res/QCouponClosingTopResDto.java
  src/main/generated/com/appcenter/marketplace/domain/local/QLocal.java
  src/main/generated/com/appcenter/marketplace/domain/market/QMarket.java
  src/main/generated/com/appcenter/marketplace/domain/metro/QMetro.java
  src/main/java/com/appcenter/marketplace/domain/coupon/Coupon.java
  src/main/java/com/appcenter/marketplace/domain/coupon/controller/CouponController.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponClosingTopResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/coupon/repository/CouponRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/CouponService.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/impl/CouponServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/member/Member.java
  src/main/java/com/appcenter/marketplace/domain/member_coupon/service/impl/MemberCouponServiceImpl.java
  src/main/java/com/appcenter/marketplace/global/common/StatusCode.java
Labels: 기능구현, 리팩토링

#67 [Refactor/#62] 마감임박, 최신 등록 쿠폰 & 리스트 조회 Endpoint 변경
  src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QCouponClosingTopResDto.java
  src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QCouponLatestTopResDto.java
  src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QMarketCouponResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/controller/CouponController.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponMarketPageResDto.java
  src/main/java/com/appcenter/marketplace/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/coupon/repository/CouponRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/CouponService.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/impl/CouponServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/controller/MarketController.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/res/CouponClosingTopResDto.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/res/CouponLatestTopResDto.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/res/MarketCouponPageResDto.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/res/MarketCouponResDto.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/service/MarketService.java
  src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketServiceImpl.java
Labels: 리팩토링

#71 [Issue/#70] 가장 많은 찜 순 매장 페이징 조회 관련 멤버 찜 여부 추가 & 데이터 건너 뜀 방지 조건 추가
  src/main/java/com/appcenter/marketplace/domain/market/controller/MarketController.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/service/MarketService.java
  src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketServiceImpl.java
Labels: 기능구현, 리팩토링, 문서화, 이슈해결
