Repository MarketPlace-O2O-Platform/MarketPlace-Server, pull requests merged in 2025-01, with the labels that each got.

#86 [Feat/#85] 요청 매장 생성, 조회 api 구현
  src/main/generated/com/appcenter/marketplace/domain/requestMarket/QRequestMarket.java
  src/main/generated/com/appcenter/marketplace/domain/requestMarket/dto/res/QRequestMarketRes.java
  src/main/java/com/appcenter/marketplace/domain/requestMarket/RequestMarket.java
  src/main/java/com/appcenter/marketplace/domain/requestMarket/controller/RequestMarketController.java
  src/main/java/com/appcenter/marketplace/domain/requestMarket/dto/req/RequestMarketCreateReq.java
  src/main/java/com/appcenter/marketplace/domain/requestMarket/dto/res/RequestMarketRes.java
  src/main/java/com/appcenter/marketplace/domain/requestMarket/repository/RequestMarketRepository.java
  src/main/java/com/appcenter/marketplace/domain/requestMarket/service/RequestMarketService.java
  src/main/java/com/appcenter/marketplace/domain/requestMarket/service/impl/RequestMarketServiceImpl.java
Labels: 기능구현

#91 [Feat/#90] 회원 공감권 스케줄링 및 로직 추가
  src/main/generated/com/appcenter/marketplace/domain/cheer/QCheer.java
  src/main/generated/com/appcenter/marketplace/domain/member/QMember.java
  src/main/generated/com/appcenter/marketplace/domain/tempMarket/QTempMarket.java
  src/main/generated/com/appcenter/marketplace/domain/tempMarket/dto/res/QTempMarketRes.java
  src/main/java/com/appcenter/marketplace/MarketplaceApplication.java
  src/main/java/com/appcenter/marketplace/domain/cheer/Cheer.java
  src/main/java/com/appcenter/marketplace/domain/cheer/CheerRepository.java
  src/main/java/com/appcenter/marketplace/domain/cheer/controller/CheerController.java
  src/main/java/com/appcenter/marketplace/domain/cheer/service/CheerService.java
  src/main/java/com/appcenter/marketplace/domain/cheer/service/impl/CheerServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/favorite/service/impl/FavoriteServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/member/Member.java
  src/main/java/com/appcenter/marketplace/domain/member/MemberRepository.java
  src/main/java/com/appcenter/marketplace/domain/member/dto/req/MemberLoginReq.java
  src/main/java/com/appcenter/marketplace/domain/member/repository/MemberRepository.java
  src/main/java/com/appcenter/marketplace/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/appcenter/marketplace/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/member_coupon/service/impl/MemberCouponServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/TempMarket.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/controller/TempMarketAdminController.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/controller/TempMarketController.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/dto/req/TempMarketReq.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/dto/res/TempMarketDetailRes.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/dto/res/TempMarketHiddenRes.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/dto/res/TempMarketPageRes.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/dto/res/TempMarketRes.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/repository/TempMarketRepository.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/repository/TempMarketRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/repository/TempMarketRepositoryImpl.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/service/TempMarketAdminService.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/service/TempMarketService.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/service/impl/TempMarketAdminServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/service/impl/TempMarketServiceImpl.java
  src/main/java/com/appcenter/marketplace/global/common/StatusCode.java
  src/main/java/com/appcenter/marketplace/global/scheduler/CheerTicketScheduler.java
Labels: 기능구현, 리팩토링, 환경 설정

#96 [Feat/#88] 매장 검색 api 구현
  build.gradle
  src/main/java/com/appcenter/marketplace/domain/market/controller/MarketController.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/res/MarketSearchRes.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepository.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/service/MarketService.java
  src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketServiceImpl.java
  src/main/java/com/appcenter/marketplace/global/common/StatusCode.java
Labels: 기능구현, 리팩토링, 환경 설정

#95 [Refactor/#92] 임시매장 등록 시 요청 매장 삭제 로직 추가 & 페이징 처리 & 숨김처리 필터링 적용
  src/main/java/com/appcenter/marketplace/MarketplaceApplication.java
  src/main/java/com/appcenter/marketplace/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/requestMarket/repository/RequestMarketRepository.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/controller/TempMarketAdminController.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/repository/TempMarketRepositoryImpl.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/service/TempMarketAdminService.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/service/impl/TempMarketAdminServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/service/impl/TempMarketServiceImpl.java
  src/main/java/com/appcenter/marketplace/global/common/StatusCode.java
Labels: 기능구현, 리팩토링

#98 [Issue/#94] 리팩토링 및 오류 해결
  src/main/generated/com/appcenter/marketplace/domain/market/dto/res/QMarketRes.java
  src/main/java/com/appcenter/marketplace/domain/market/Market.java
  src/main/java/com/appcenter/marketplace/domain/market/controller/MarketController.java
  src/main/java/com/appcenter/marketplace/domain/market/controller/MarketOwnerController.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/req/MarketReq.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/req/MarketUpdateReq.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/res/MarketRes.java
  src/main/java/com/appcenter/marketplace/domain/market/dto/res/TopFavoriteMarketRes.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/market/repository/MarketRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/service/MarketOwnerService.java
  src/main/java/com/appcenter/marketplace/domain/market/service/MarketService.java
  src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketOwnerServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/service/impl/MarketServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/requestMarket/controller/RequestMarketController.java
  src/main/java/com/appcenter/marketplace/domain/requestMarket/service/RequestMarketService.java
  src/main/java/com/appcenter/marketplace/domain/requestMarket/service/impl/RequestMarketServiceImpl.java
Labels: 리팩토링, 이슈해결

#99 [Refactor/#93] 쿠폰 관련 리팩토링 진행
  src/main/java/com/appcenter/marketplace/domain/cheer/controller/CheerController.java
  src/main/java/com/appcenter/marketplace/domain/coupon/Coupon.java
  src/main/java/com/appcenter/marketplace/domain/coupon/controller/CouponController.java
  src/main/java/com/appcenter/marketplace/domain/coupon/controller/CouponOwnerController.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponPageRes.java
  src/main/java/com/appcenter/marketplace/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/coupon/repository/CouponRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/CouponOwnerService.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/CouponService.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/impl/CouponOwnerServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/impl/CouponServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/market/controller/MarketController.java
  src/main/java/com/appcenter/marketplace/domain/member_coupon/MemberCouponType.java
  src/main/java/com/appcenter/marketplace/domain/member_coupon/controller/MemberCouponController.java
  src/main/java/com/appcenter/marketplace/domain/member_coupon/repository/MemberCouponRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/member_coupon/repository/MemberCouponRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/member_coupon/service/MemberCouponService.java
  src/main/java/com/appcenter/marketplace/domain/member_coupon/service/impl/MemberCouponServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/requestMarket/service/RequestMarketService.java
  src/main/java/com/appcenter/marketplace/domain/requestMarket/service/impl/RequestMarketServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/controller/TempMarketAdminController.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/service/TempMarketAdminService.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/service/impl/TempMarketAdminServiceImpl.java
Labels: 리팩토링

#102 [Refactor/#93] 회원의 쿠폰 리스트 조회시 url 통일
  src/main/java/com/appcenter/marketplace/MarketplaceApplication.java
  src/main/java/com/appcenter/marketplace/domain/member_coupon/controller/MemberCouponController.java
Labels: 리팩토링

#106 [Refactor/#105] 쿠폰 리팩토링 및 기능 추가
  src/main/generated/com/appcenter/marketplace/domain/coupon/dto/res/QCouponMemberRes.java
  src/main/generated/com/appcenter/marketplace/domain/coupon/dto/res/QCouponRes.java
  src/main/generated/com/appcenter/marketplace/domain/coupon/dto/res/QLatestCouponRes.java
  src/main/java/com/appcenter/marketplace/domain/coupon/controller/CouponController.java
  src/main/java/com/appcenter/marketplace/domain/coupon/controller/CouponOwnerController.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/req/CouponUpdateReq.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponHiddenRes.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponMemberRes.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/CouponRes.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/LatestCouponRes.java
  src/main/java/com/appcenter/marketplace/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/coupon/repository/CouponRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/CouponOwnerService.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/CouponService.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/impl/CouponOwnerServiceImpl.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/impl/CouponServiceImpl.java
Labels: 기능구현, 리팩토링

#108 [Feat] 임시 매장 페이징 검색 api 구현
  src/main/java/com/appcenter/marketplace/domain/tempMarket/controller/TempMarketController.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/dto/res/TempMarketRes.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/service/TempMarketService.java
  src/main/java/com/appcenter/marketplace/domain/tempMarket/service/impl/TempMarketServiceImpl.java
Labels: 기능구현, 리팩토링

#110 [Feat/#100] 발급 쿠폰(member_coupon)의 count 내림차순 인기 쿠폰(coupon) 조회 페이징 구현
  src/main/generated/com/appcenter/marketplace/domain/coupon/dto/res/QPopularCouponRes.java
  src/main/java/com/appcenter/marketplace/domain/coupon/controller/CouponController.java
  src/main/java/com/appcenter/marketplace/domain/coupon/dto/res/PopularCouponRes.java
  src/main/java/com/appcenter/marketplace/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/appcenter/marketplace/domain/coupon/repository/CouponRepositoryCustomImpl.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/CouponService.java
  src/main/java/com/appcenter/marketplace/domain/coupon/service/impl/CouponServiceImpl.java
Labels: 기능구현, 리팩토링
